title: Jaime Pignatelli
description: My personal website and blog about technology, software development, and other topics.
author: Jaime Pignatelli
email: no-reply@example.com
baseurl: "" # Leave empty for GitHub Pages
url: https://jaipi.github.io
sass:
  style: compressed
remote_theme: hydecorp/hydejack

plugins:
  - jekyll-remote-theme # Enables the use of remote themes
  - jekyll-feed # Generates an Atom feed
  - jekyll-seo-tag # Adds SEO meta tags
  - jekyll-sitemap # Generates a sitemap for search engines
  - jekyll-paginate # Enables pagination (optional, for blogs)
social:
  github: https://github.com/JaiPi
  linkedin: https://www.linkedin.com/in/jaimepignatelli/

markdown: kramdown
highlighter: rouge
